-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3307
-- Generation Time: Sep 17, 2025 at 10:48 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.0.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `outeralert`
--

-- --------------------------------------------------------

--
-- Table structure for table `articles`
--

CREATE TABLE `articles` (
  `id` int(11) NOT NULL,
  `articleTitle` varchar(255) NOT NULL,
  `articleSub` varchar(500) DEFAULT NULL,
  `articleImage` varchar(255) DEFAULT NULL,
  `articleContent` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `articles`
--

INSERT INTO `articles` (`id`, `articleTitle`, `articleSub`, `articleImage`, `articleContent`, `created_at`, `updated_at`) VALUES
(1, 'Build A Kit', 'Think you need for survival.', 'kit1.jpg', 'During the disaster, you may need a thing or two basic items to be able to hold on for a few days. Being prepared all the time do not means that you can hold for your lifes too long. Heres the list of basic item and element that may fit inside your kit in case of emergency.\r\n\r\n 1. Water\r\n 2. Food\r\n 3. Flashlight\r\n 4. Local Maps\r\n 5. Cell Phone with charges and backup battery\r\n 6. Moist toweletters, garbage bags and plastic ties.', '2025-08-20 05:52:37', '2025-08-20 16:01:41'),
(2, 'To Do In Blackout?', 'Dont be afraid, have some faith!', 'blackout2.jpg', 'Power Outages sometime occurs during the days of our lives and may still happened occasionally from time to time. Such damage to power transmission cable or equipment at a substation. To prevent being outsourced, we can prepared with some contingency plans and back-up measures that can help individuals, households to mitigate the risks and reduce the impact of a power outrage.\r\n\r\nIn power cut we can always make sure to have some food and drink avaliable that doesnt require electricity to heat or prepare it, switch off all the eletrcial appliances that are not designed to run unattended such as cookers, grills and electrics fires, have some blankets and thick clothes and easily accessible and make sure to have more essesntial medical equipment and back up for extra support.', '2025-08-20 08:09:17', '2025-08-20 16:00:54'),
(3, 'Tsunami', 'A Shocking Wave!', 'tsunami3.jpg', 'Tsunamis, know as \'habour waves\', are giant waves caused by earthquakes or volcanic eruptions under the sea. They are generated by the displacement of a large volume of water. Earthquakes, particulary those occuring on the sea floor are the most freqently due to it transfer its high amount of energy from earthquake to tsunami.\r\n\r\nA tsunami can sometimes reaching heights of over 100 feet (30.5 meters), onto land. These walls of water can cause widespread destruction and death when they crash ashore. The 2011 earthquake had caused the tsunami to swept away over 15,000 lives of people in Tohoku, Japan.\r\n\r\nBe sure to piroritize yourself in safety during the run: gained yourself enough in high ground and inland areas, espacially in an earthquake tsunami zone. If you feel a strong earthquake, make sure to immediately evacuate to higher ground without waiting for an official warning.', '2025-08-20 08:11:58', '2025-08-20 08:41:46'),
(4, 'Disaster Preparadness', 'Don\'t Wait Until Last Minutes!', 'disaster4.jpg', 'Disaster and natural events comes twice occasionally in a month, that doesn\'t mean that you are safe within kilometers to your home! Please do not wait until last minutes when the accident happened and brace yourself for the impact to help yourself, your freinds and your family. \r\n\r\n1. Pick a place to meet after disaster\r\n- Choose one right outside your home, your neighbour\'s house or even your friends house in case of suddent household emergency such as fire, earthquake and flood. If the situation is dangerous enough to make a demand, it is best not to return home soon after the disaster has evaded.\r\n\r\n2. Teach your childs to do 9-1-1 Call\r\n- Post relevant emergency number for public servants such as police, ambulance, fire fighters and civil service for help. Be sure to kept them in the notes so that it is easier to make a phone call based on dire situation.\r\n\r\n3. Keep an emergency supply kit\r\n- you should also keep a smaller version of your first-aid kit for emergency in case of injuries and accidents.\r\n\r\n4. Read information regrading your place\r\n- Be well-informed on your city, state and country by logging on website such as meteorological web page and latest news to keep track of current event during tense situation. You can also keep a copy of the address and telephone number for informations that is neccessity when internet connectivity isn\'t avaliable at the moment.\r\n\r\n5. Conduct drills practice\r\n- Practice make everything perfect. You can conduct safety meassure by conducing drills and practices on evacuating twice a year, theme such as driving to planned location, recognize evacuation route, plot alternate route and ensuring shortcuts.\r\n\r\nThere were many lists of where the preparedness tips should be. Users is welcome to check on your gorvenment websites to listen for more advice on how to ensuring one\'s safety.', '2025-08-20 16:18:27', '2025-08-20 16:18:27'),
(5, 'How to perform CPR', 'The lives are at stake!', 'cpr5.jpg', 'CPR, Known as \'Cardiopulmonary Resuscitation\' is a rescue method that help someone to revive their cardiac arrest by doing ches compressions. During disaster, trauma shock and breathing problem tends to make people ill. You can start taking immediate action when meting people with this condition.\r\n\r\nType of CPR:\r\n1. Hands-only CPR\r\n- Push hard and fast in the center of the person chest more then 100 to 120 times per minutes.\r\n\r\n2. CPR with breaths:\r\n- You give chest compression and pause to give person two mouth-to-mouth rescue breath(this isn\'t kiss.).Give at east 30 compressions\r\n\r\nBefore starting to do CPR, you need to ask someone nearby for an antomated external defibrillator (AED) or call 911. Think of ABC when doing it:\r\n\r\nA = AIRWAY\r\n- Tilt the person\'s head back while they was lying on their back, look in their mouth and throat to see if there anything stuck beneath it.\r\n\r\nB = BREATHING\r\n- Lean in close to their face and listen for 10 seconds to see if your hear them breathing. \r\n\r\nC = CIRCULATION\r\n- Check for a pulse, and feel the side of their neck below the jawline for a second to see the breathing start to effects.\r\n\r\nTo Do CPR on Chest Compressions:\r\n1. Put your hands over the other and place them in the middle of the person\'s chest.\r\n2. Push your hands down hard in the middle of their chest for a second. Use the heel of your hands or the part just before your wrist.\r\n3. Repeateadly push on person\'s chest 100 to 120 times per minutes\r\n4. Make sure allow their chets come all the way back up between compressions.\r\n\r\nTo Do Rescue Breaths:\r\n1. Pinch their nose closed while titling their heads back a little and their chin up.\r\n2. Close your mouth and blow a normal-sized breath into it.\r\n3. If the person\'s chest doesn\'t come up, check to see if there\'s something in their mouth.', '2025-08-20 16:34:02', '2025-08-20 16:34:02');

-- --------------------------------------------------------

--
-- Table structure for table `bugs`
--

CREATE TABLE `bugs` (
  `id` int(11) NOT NULL,
  `bugsType` text DEFAULT NULL,
  `bugsDesc` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `checklists`
--

CREATE TABLE `checklists` (
  `id` int(11) NOT NULL,
  `userId` int(11) NOT NULL,
  `checklistTitle` varchar(255) NOT NULL,
  `dateCreated` date DEFAULT curdate(),
  `timeCreated` time NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `checklistsitems`
--

CREATE TABLE `checklistsitems` (
  `id` int(11) NOT NULL,
  `checklistsId` int(11) NOT NULL,
  `checklistDesc` text NOT NULL,
  `status` enum('done','not_done') DEFAULT 'not_done',
  `dateCreated` date DEFAULT curdate(),
  `timeCreated` time DEFAULT curtime()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `feedback`
--

CREATE TABLE `feedback` (
  `id` int(11) NOT NULL,
  `usedFrequent` text DEFAULT NULL,
  `usedFeature` text DEFAULT NULL,
  `usedDislike` text DEFAULT NULL,
  `usedImprovement` text DEFAULT NULL,
  `usedRating` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `questions`
--

CREATE TABLE `questions` (
  `id` int(11) NOT NULL,
  `topic` varchar(100) DEFAULT NULL,
  `questionText` text DEFAULT NULL,
  `optionA` text DEFAULT NULL,
  `optionB` text DEFAULT NULL,
  `optionC` text DEFAULT NULL,
  `optionD` text DEFAULT NULL,
  `correctOption` char(1) DEFAULT NULL,
  `level` int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`id`, `topic`, `questionText`, `optionA`, `optionB`, `optionC`, `optionD`, `correctOption`, `level`) VALUES
(1, 'firstAid', 'What is the first step in administering CPR to a patient?', 'Check for responsiveness', 'call emergency services', 'begin chest compressions', 'Give rescue breaths', 'A', 1),
(2, 'firstAid', 'How long should you apply preassure to stop the bleeding?', '1 minutes', '5 minutes', 'Until bleeding stop', 'Do nothing', 'C', 1),
(3, 'firstAid', 'Which of following bandages is best material for a sterile dressing?', 'Cotton Wool', 'Gauze', 'Cloth Towel', 'Paper Towel', 'B', 1),
(4, 'firstAid', 'When removing a bandage, you should: ', 'Cut it off with scissors to avoid pain', 'Loosen it gradually to prevent tissue damage', 'pull it quickly at first thought', 'remove it immediately regardless of easing the pain of it', 'B', 1),
(5, 'firstAid', 'Which of the following signs showing severe bleeding?', 'Blood spurting from wound', 'Blood that is slow and steady', 'No bleeding', 'Small amount of blood on the surface', 'A', 1),
(6, 'firstAid', 'During disaster, what is the best way to prevent shock?', 'Allow them to walk around with pain', 'Give them treatment such as food and water', 'Ignore symptoms altogether', 'Keep the victim warm and comfortable', 'D', 1),
(7, 'firstAid', 'What is important when helping a disaster victim?', 'Taking photographs', 'Saving belongings', 'Personal Safety', 'Move them quickly', 'C', 1),
(8, 'firstAid', 'When a person is unconscious, you need to: ', 'Check for responsiveness and breathing', 'Give them water', 'Beat the patient to ensure their heart starts beating', 'Offer them food and drinks', 'A', 1),
(9, 'firstAid', 'The correct way to treat a person with hypothermia is: ', 'Remove their wet clothes and cover them with warm blankets', 'Give them water to drink', 'Leave them in a warm place to recover', 'Rub their limbs to generate heat', 'A', 1),
(10, 'firstAid', 'What substance is the most appropriate for chemical burn first aid?', 'Oil', 'Ice', 'Sand', 'Water', 'D', 1),
(11, 'electric', 'Why do you need to unplug appliances during a storm?', 'To save electricity and reduce bills.', 'To prevent power surges from damaging them.', 'To make it easier for utility crews to restore power.', 'Avoid risks caused by lightning strikes.', 'B', 1),
(12, 'electric', 'Why is it dangerous to use a portable generator indoors?', 'It creates fire hazards.', 'It produces loud noise.', 'It emits carbon monoxide.', 'It produces loud noise.', 'C', 1),
(13, 'electric', 'During a power outage, which is the safest way to provide temporary lighting in your home?', 'Using a portable generator', 'Using candles in multiple locations.', 'Using battery-operated flashlights.', 'Using a car battery with jumper cables.', 'C', 1),
(14, 'electric', 'If you see a downed power line, what is the first thing you should do?', 'Touch it with a stick.', 'Call the power company or 911.', 'Move out of the harm’s way.', 'Pour water on it.', 'B', 1),
(15, 'electric', 'What is a brownout?', 'A temporary drop in voltage.', 'A complete loss of power.', 'A surge in voltage.', 'A specific type of lightning strike.', 'A', 1),
(16, 'electric', 'What should you do before entering a flooded basement?', 'Turn off the main power.', 'Check if the water is clear.', 'Check for damage.', 'Try to open a window for ventilation.', 'A', 1),
(17, 'electric', 'What is the main cause of electrical fires?', 'Overloaded circuits.', 'Faulty wiring.', 'Misused appliances.', 'All of the above.', 'D', 1),
(18, 'electric', 'The main danger associated with downed power lines is:', 'Fire hazard.', 'Electrocution.', 'Tipping hazard.', 'Communication disruption.', 'B', 1),
(19, 'electric', 'The term that describes the danger zone around a downed power line where electricity can energize the ground is:', 'Ground current.', 'Step potential.', 'Ground gradient.', 'All of the above.', 'D', 1),
(20, 'electric', 'If sparks come out from an outlet, what should you do immediately?', 'Cover it with a piece of tape.', 'Unplug everything and turn off the power.', 'Use a fire extinguisher.', 'Ignore it.', 'B', 1),
(21, 'blackout', 'What is the most important items to have in an emergency kit for a blackout?', 'Television', 'Flashlight with extra batteries', 'Electric fan', 'Laptop', 'B', 1),
(22, 'blackout', 'The safest way to get information and emergency alerts during blackout is:', 'Coping by listening music', 'Use a landline phone', 'Tune in radio', 'Use a computer with backup battery', 'C', 1),
(23, 'blackout', 'Which following is not a good source of light during blackout', 'Battery-powered lantern', 'Headlamp', 'Candle', 'Glow stick', 'C', 1),
(24, 'blackout', 'What is the recommended supply of water and non-perishable food for a household emergency kit?', 'One day', 'Three day', 'One week', 'One month', 'B', 1),
(25, 'blackout', 'The most common cause of blackout could be: ', 'Electrical grid overloading', 'Powerline incident', 'Severe storms or weather', 'All of the above', 'D', 1),
(26, 'blackout', 'What do you need to avoid doing a blackout?', 'Using open flames for lighting', 'Unplugging appliances', 'Tune in radio', 'Staying indoors if safe', 'A', 1),
(27, 'blackout', 'How long can food typically stay safe in the refrigerator during blackout?', 'About 4 hours', 'About 24 hours', 'About 48 hours', 'Up to 72 hours', 'D', 1),
(28, 'blackout', 'Why must we stay home during blackout?', 'To keep warm', 'To prevent theft', 'To avoid falling debris and power lines', 'To watch portable television', 'C', 1),
(29, 'blackout', 'Why it was dangerous to use candles during blackout?', 'They produce carbon monoxide', 'They may cause a fire if left unattended', 'They attract insects', 'They are not bright to cover the house', 'B', 1),
(30, 'blackout', 'How do you conserve battery power during blackout?', 'Turn off unnecessary devices', 'Keep devices on standby', 'Use multiple devices at once', 'Keep devices plugged in', 'A', 1),
(31, 'earthquake', 'What should you do immediately after feeling an earthquake?', 'Run outside as fast as you can', 'Drop, cover and hold on', 'Call emergency services', 'Turn off the gas and electricity', 'B', 1),
(32, 'earthquake', 'The safest place to take cover indoors is:', 'Under a heavy piece of furniture', 'Near windows', 'Against an Exterior wall', 'Under a sturdy table or desk', 'D', 1),
(33, 'earthquake', 'Which of the following is NOT recommended during earthquake', 'Staying in bed', 'Running outdoors', 'Taking cover under furniture', 'Staying away from heavy objects that could fall', 'B', 1),
(34, 'earthquake', 'What do you do when you are outdoors when earthquake occurs?', 'Seek shelter under tree', 'Move to an open area', 'Stand next to a building', 'Run into nearby building', 'B', 1),
(35, 'earthquake', 'How should you check for injuries?', 'Move injured person to protection shelter', 'Avoid moving injured person unless there is immediate danger', 'Offer water and food', 'Ignore injuries and pain', 'B', 1),
(36, 'earthquake', 'What is Aftershock mean?', 'Tsunami caused by earthquake', 'Earthquake occurs in different region', 'Volcanic eruption', 'Small earthquake', 'D', 1),
(37, 'earthquake', 'What is the recommended action during an earthquake when a building begins to collapse?', 'Run outside', 'Drop, cover and stay', 'Climb to the rooftop', 'Exit immediately through the nearest door', 'B', 1),
(38, 'earthquake', 'How can you prepare your home for an earthquake?', 'Secure heavy furniture and objects', 'Keep all windows open', 'Paint the walls bright colors', 'Install more unbreakable mirror', 'A', 1),
(39, 'earthquake', 'What should you avoid during an earthquake?', 'Using elevators', 'Checking for damages carefully', 'Turning off utilities', 'Waiting for official clearance', 'A', 1),
(40, 'earthquake', 'An effective way to communicate after an earthquake is:', 'Send smoke signals', 'Shout loudly', 'Use mobile phone', 'Send carrier pigeons', 'C', 1),
(41, 'tsunami', 'What is tsunami?', 'A large ocean caused by underwater earthquake or volcanic eruptions', 'A strong windstorm over the ocean', 'Hurricane', 'A tide wave', 'A', 1),
(42, 'tsunami', 'The primary danger of a tsunami:', 'High winds', 'Massive flooding and destruction', 'Lightning strikes', 'Falling objects', 'B', 1),
(43, 'tsunami', 'How much warning time is typically available before a tsunami hits an underwater earthquake?', 'Several hours', 'Several days', 'Few minutes to an hour', 'Several weeks', 'C', 1),
(44, 'tsunami', 'What should you do during a tsunami?', 'Stay on the beach', 'Go to the shoreline', 'Stay in your car', 'Listen to local authorities and evacuate', 'D', 1),
(45, 'tsunami', 'If you are caught in a tsunami and cannot evacuate, you should:', 'Climb to the highest possible point', 'Try to swim against the current', 'Climb onto a sturdy roof or structure', 'Grab a boat and try to escape', 'C', 1),
(46, 'tsunami', 'What natural sign indicates an impending tsunami?', 'Sudden receding of the ocean', 'Calm, still water', 'Sudden increase in wind speed', 'Thunderstorm', 'A', 1),
(47, 'tsunami', 'How high a tsunami can reach?', 'Up to 10 meters', 'Over 30 meters', 'A few centimeters', 'Never more than 5 meters', 'B', 1),
(48, 'tsunami', 'What should you pack if you have to evacuate due to tsunami?', 'Essential supplies like food, water, and medication', 'Clothes', 'Pet', 'Run', 'A', 1),
(49, 'tsunami', 'The main key feature of a tsunami is:', 'Detection buoys and seismic sensors', 'Weather balloons', 'Radio broadcast', 'None of the above', 'A', 1),
(50, 'tsunami', 'Why it is dangerous to go back to the coast after tsunami?', 'Water is dirty', 'Beach is closed for renovation', 'Area may still be unstable', 'All of the above', 'C', 1),
(51, 'flashflood', 'The primary root cause of the flashfoold is:', 'Heavy rainfall', 'Tsunami waves', 'Coastal erosion', 'Drought conditions', 'A', 1),
(52, 'flashflood', 'What is the safest action during a flash flood?', 'Seek shelter under trees', 'Move to higher ground quickly and calmly', 'Enter basement', 'Cross flooded street on foot', 'B', 1),
(53, 'flashflood', 'Why it is dangerous to drive through floodwaters?', 'Water is deeper than it appears', 'There could be strong currents', 'Floodwaters can hide hazards and debris', 'All of the above', 'D', 1),
(54, 'flashflood', 'What should you NOT do during the flashflood?', 'Playingin the middle of flashflood', 'Collecting you valuable items', 'Use electronic appliances', 'All of the above', 'D', 1),
(55, 'flashflood', 'If you cannot evacuate, what should you do?', 'Climb to the roof of your house', 'Seek higher ground within the building', 'Use a boast to navigate the floodwaters', 'Stay in the basement', 'B', 1),
(56, 'flashflood', 'What are the early warning signs for an impending flash flood?', 'Rapidly rising water levels', 'Heavy rainfall', 'Sudden increase in river flow', 'All of the above', 'D', 1),
(57, 'flashflood', 'What should be part of an emergency kit for flash flood preparedness?', 'Drinking water and food', 'Flashlight and batteries', 'First aid supplies', 'All of the above', 'D', 1),
(58, 'flashflood', 'The most important safety rule during flash flood is:', 'Never attempt to cross the water by foot', 'Use electrical appliances during flood to stay informed', 'Sleep in the basement', 'Ignore weather alerts', 'A', 1),
(59, 'flashflood', 'How can you prepare your home for a possible flash flood?', 'Seal windoes and doors tightly', 'Store documents', 'Elevate electrical appliances and utilities', 'Remove all sandbags around the house', 'C', 1),
(60, 'flashflood', 'What is the primary danger of flash floods?', 'Freezing temperature', 'Electrocution and drowning', 'Lack of oxygen', 'Allergic reaction', 'B', 1),
(61, 'fireSafety', 'What is important to have a fire escape plan?', 'Know how to use a fire extinguisher', 'Ensure everyone escape quickly and safety', 'To prevent fires from starting', 'To keep fire insurances costs low', 'B', 1),
(62, 'fireSafety', 'The safest way to exit a building during a fire is', 'Use elevator', 'Break a window immediately', 'Crawl low under smoke', 'Run straight to the front door', 'C', 1),
(63, 'fireSafety', 'What should you do if your clothes catch fire?', 'Run and scream', 'smother the flames with a blanket or towel', 'Cover the fire with wet cloth', 'Stop, drop and roll to extinguish the fire', 'D', 1),
(64, 'fireSafety', 'Why it was dangerous to open doors during a fire', 'It cause fire to spread rapidly', 'It wil let in cold air', 'It make it harder to see due to smoke', 'It was frustrating', 'A', 1),
(65, 'fireSafety', 'If trapped inside a burning building, you should:', 'Stay close to the floor and look for a safe exit', 'Hide in a closet', 'Break a window immediately', 'Call 911', 'A', 1),
(66, 'fireSafety', 'Why is it important to keep fire exits clear', 'To prevent fire from spreading', 'To ensure quick evacuation', 'To allow firefighters to enter easily', 'All of the above', 'B', 1),
(67, 'fireSafety', 'Common safety feature in building to prevent fire spread is:', 'Fire doors and partitions', 'Glass walls', 'Carpeted floors', 'Open staircases', 'A', 1),
(68, 'fireSafety', 'What is the most common cause of house fires', 'Cooking accidents', 'Electrical faults', 'Heating equipment', 'Cigarettes', 'A', 1),
(69, 'fireSafety', 'Which type of fire extinguisher is suitable for electrical fire?', 'Water extinguisher', 'Foam extinguisher', 'CO2 extinguisher', 'Dry power extinguisher', 'C', 1),
(70, 'fireSafety', 'Which following is a good fire safety habit', 'Leaving candles unattended', 'Turning off appliance', 'Overloading eletrical outlets', 'Ignoring smoke alarms', 'B', 1);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `contactNumber` varchar(20) DEFAULT NULL,
  `profilePic` text DEFAULT NULL,
  `xp` int(11) DEFAULT 0,
  `level` int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `bugs`
--
ALTER TABLE `bugs`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `checklists`
--
ALTER TABLE `checklists`
  ADD PRIMARY KEY (`id`),
  ADD KEY `checklists_ibfk_1` (`userId`);

--
-- Indexes for table `checklistsitems`
--
ALTER TABLE `checklistsitems`
  ADD PRIMARY KEY (`id`),
  ADD KEY `checklistsitems_ibfk_1` (`checklistsId`);

--
-- Indexes for table `feedback`
--
ALTER TABLE `feedback`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `questions`
--
ALTER TABLE `questions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `bugs`
--
ALTER TABLE `bugs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `checklists`
--
ALTER TABLE `checklists`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `checklistsitems`
--
ALTER TABLE `checklistsitems`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `feedback`
--
ALTER TABLE `feedback`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `questions`
--
ALTER TABLE `questions`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=71;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `checklists`
--
ALTER TABLE `checklists`
  ADD CONSTRAINT `checklists_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `checklistsitems`
--
ALTER TABLE `checklistsitems`
  ADD CONSTRAINT `checklistsitems_ibfk_1` FOREIGN KEY (`checklistsId`) REFERENCES `checklists` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
